# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: ReversingLabs.SpectraResolve
PackageVersion: 1.1.1
PackageLocale: en-US
Publisher: ReversingLabs
PackageName: Spectra Resolve
License: Spectra Resolve - EULA
ShortDescription: Scan your projects dependencies for supply chain risks, and work through the fixes with a coding agent.
ManifestType: defaultLocale
ManifestVersion: 1.12.0
