# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ReversingLabs.SpectraResolve
PackageVersion: 1.1.1
InstallerType: zip
NestedInstallerType: nullsoft
NestedInstallerFiles:
- RelativeFilePath: resolve\Spectra-Resolve-Setup-1.1.1-x64.exe
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.secure.software/rlResolve111-Windows-x64.zip
  InstallerSha256: 59151702917E80906A487BF13A8A5B68236B971DD3045F5A6F1BA70DB4EA1CD5
ManifestType: installer
ManifestVersion: 1.12.0
